development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>
  channel_prefix: backend_production

test:
  adapter: test
