development:
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>

test:
  url: redis://127.0.0.1:6379/2

production:
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/1" } %>
